name: coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15
    name: "coverage"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install lcov by Homebrew
      run: brew install lcov
    - name: Build && Test && Upload
      run: .ci/build_coverage.sh
