name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        # https://github.com/actions/virtual-environments/tree/main/images/linux
        - { os: "ubuntu-20.04", cc: "gcc-10", cxx: "g++-10" }
        - { os: "ubuntu-20.04", cc: "clang-10", cxx: "clang++-10" }
    name: "${{matrix.config.cxx}}"
    steps:
    - name: Setup
      run: sudo apt-get -y install "${{matrix.config.cc}}" "${{matrix.config.cxx}}"
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build && Test
      run: .ci/build_linux.sh
      env: { CC: "${{matrix.config.cc}}", CXX: "${{matrix.config.cxx}}" }
