name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        # https://github.com/actions/virtual-environments/tree/main/images/win
        - { os: "windows-2016", vs: "Visual Studio 2017", arch: "x86" }
        - { os: "windows-2016", vs: "Visual Studio 2017", arch: "x64" }
        - { os: "windows-2019", vs: "Visual Studio 2019", arch: "x86" }
        - { os: "windows-2019", vs: "Visual Studio 2019", arch: "x64" }
    name: "${{matrix.config.vs}} ${{matrix.config.arch}}"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build && Test
      run: .ci\build_windows_${{matrix.config.arch}}.bat
