name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        # https://github.com/actions/virtual-environments/tree/main/images/win
        - { os: "windows-2019", vc: "msvc2019", arch: "x86" }
        - { os: "windows-2019", vc: "msvc2019", arch: "x64" }
        - { os: "windows-2022", vc: "msvc2022", arch: "x86" }
        - { os: "windows-2022", vc: "msvc2022", arch: "x64" }
    name: "${{matrix.config.vc}} ${{matrix.config.arch}}"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build && Test
      run: |
        cmake --preset windows-${{matrix.config.arch}}-${{matrix.config.vc}}
        cmake --build --preset windows-${{matrix.config.arch}}-${{matrix.config.vc}}-release
        ctest --preset windows-${{matrix.config.arch}}-${{matrix.config.vc}}-release
