name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        # https://github.com/actions/virtual-environments/tree/main/images/win
        - { os: "windows-2019", vc: "msvc2019", arch: "x86" }
        - { os: "windows-2019", vc: "msvc2019", arch: "x64" }
        - { os: "windows-2022", vc: "msvc2022", arch: "x86" }
        - { os: "windows-2022", vc: "msvc2022", arch: "x64" }
    name: "${{matrix.config.vc}} ${{matrix.config.arch}}"
    steps:
    - name: Setup
      run: choco install cmake ninja
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Select MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        cmake --preset windows-${{matrix.config.arch}}-${{matrix.config.vc}}
        cmake --build --preset windows-${{matrix.config.arch}}-${{matrix.config.vc}}-release
    - name: Test
      run: |
        ctest --preset windows-${{matrix.config.arch}}-${{matrix.config.vc}}-release
